- name: Generate the root password for ldap
  shell: slappasswd -s {{ ldap_data_tree_password }}
  register: root_password_hash

- name: Generate the password for config admin
  shell: slappasswd -s {{ config_admin_password }}
  register: config_admin_password_hash

- name: Setup Admin to manage config
  ldap_attr:
    dn: "olcDatabase={0}config,cn=config"
    name: "{{ item.key }}"
    values: "{{ item.value }}"
    state: exact
  with_dict:
    olcRootPW: "{{ config_admin_password_hash.stdout }}"

- name: Set up admin to manage data tree
  ldap_attr:
    dn: olcDatabase={1}mdb,cn=config
    name: "{{ item.key }}"
    values: "{{ item.value }}"
    state: exact
  with_dict:
    olcSuffix: "{{ slapd_basedn }}"
    olcRootDN: "{{ slapd_basedn_admin }}"
    olcRootPW: "{{ root_password_hash.stdout }}"
