- name: Create file for modifying LDAP access rights
  copy:
    dest: "/etc/ldap/access.ldif"
    content: |
      dn: olcDatabase={1}mdb,cn=config
      changetype: modify
      replace: olcAccess
      olcAccess: {0}to attrs=userPassword by self write by anonymous auth by * none
      olcAccess: {1}to attrs=shadowLastChange by self write by * read
      olcAccess: {2}to * by self read by * break
      olcAccess: {3}to * by users search by * break
      -

- name: Change LDAP access rights
  command: /usr/bin/ldapmodify -Q -H ldapi:/// -Y EXTERNAL -f /etc/ldap/access.ldif
