---
- name: check that variables are defined
  assert:
    that:
      - organization is defined
      - slapd_domain is defined
      - slapd_basedn is defined
      - slapd_basedn_admin is defined
      - ldap_data_tree_password is defined
      - config_admin_password is defined
      - ldap_certificate_file is defined
      - ldap_certificate_key_file is defined
      - ldap_ca_certificate_file is defined
      - perun_folder is defined

- name: Configure domain for LDAP
  debconf:
    name: 'slapd'
    question: '{{ item.question }}'
    value: '{{ item.value }}'
    vtype: '{{ item.vtype }}'
  with_items:
    - question: "slapd/domain"
      value: "{{ slapd_domain }}"
      vtype: "string"
    - question: "shared/organization"
      value: "{{ organization }}"
      vtype: "string"
    - question: "slapd/backend"
      value: "MDB"
      vtype: "string"

- name: install LDAP
  package:
    name:
      - ssl-cert
      - slapd
      - ldap-utils
      - python-ldap
      - libnet-ldap-perl
    state: present
