---
- name: Configure domain for LDAP
  debconf:
    name: 'slapd'
    question: '{{ item.question }}'
    value: '{{ item.value }}'
    vtype: '{{ item.vtype }}'
  with_items:
    - question: "slapd/domain"
      value: "{{ slapd_domain }}"
      vtype: "string"
    - question: "shared/organization"
      value: "{{ organization }}"
      vtype: "string"
    - question: "slapd/backend"
      value: "MDB"
      vtype: "string"

- name: install LDAP
  package:
    name:
      - ssl-cert
      - slapd
      - ldap-utils
      - python-ldap
      - libnet-ldap-perl
    state: present
