---
- import_tasks: check-variables.yml
  tags:
    - install-ldap
- import_tasks: install-ldap.yml
  tags:
    - install-ldap
- import_tasks: configure-ldap.yml
  tags:
    - install-ldap
- import_tasks: configure-ldap-access.yml
  tags:
    - install-ldap
- import_tasks: configure-ldap-tls.yml
  tags:
    - install-ldap
